"""empty message

Revision ID: 5e2fdaa4cb2f
Revises: 6af5fd27220d
Create Date: 2020-07-20 10:42:52.569519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2fdaa4cb2f'
down_revision = '6af5fd27220d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('cohort_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'cohorts', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'cohort_id')
    # ### end Alembic commands ###
