"""empty message

Revision ID: c003633b7cad
Revises: 341d858a61de
Create Date: 2020-07-27 03:43:25.927620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c003633b7cad'
down_revision = '341d858a61de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_assessments', sa.Column('coding', sa.Integer(), nullable=True))
    op.add_column('student_assessments', sa.Column('multiple_choice', sa.Integer(), nullable=True))
    op.add_column('student_assessments', sa.Column('overrall', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_assessments', 'overrall')
    op.drop_column('student_assessments', 'multiple_choice')
    op.drop_column('student_assessments', 'coding')
    # ### end Alembic commands ###
