"""empty message

Revision ID: eaf78f908667
Revises: 455791cc2aaa
Create Date: 2020-07-26 04:48:23.992846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf78f908667'
down_revision = '455791cc2aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohort_instructors', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohort_instructors', 'id')
    # ### end Alembic commands ###
